---
- name: Deploy docker container
  become: true
  hosts: docker-reddit-app
  tasks:
    - name: Deploy docker container
      docker_container:
        name: reddit
        image: abirvalg/otus-reddit:1.0
        state: started
        ports:
          - "80:9292"
