kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: DIfizGkOTgd5ToZ5/1L2gmMJDmlDO++2rNFeTx2GT5w=
      - identity: {}
